#!/bin/bash
#
# Inkpump cross-toolchain builder, heavily based on SLIND cross-toolchain
# builder.
#
# It is capable of operating in two modes:
#
#  1) building from git; this is default mode, and can be adjusted by passing
#  --<pkg>-tag= options. In this mode mktpkg obtains sources by checking out
#  source code from git, using passed tags and by looking at binary repository
#  and finding out corresponding source for components which are not specified
#  in command line.
#
#  2) building from provided source code. This is enabled by option
#  --manual-mode and providing source code in target-dir, in directories named
#  after components (binutils, linux-libc-dev, gcc-${VERSION}, glibc, uclibc).
#

TP_VERSION=0.3
SUITE=asimov
BDBT=/usr/share/bashdb/bashdb-trace

usage() {
	echo
	echo "Usage: $0 [--force] [--manual-mode] [--suite=<suite>] <target-arch>"
	echo
	echo "<target-arch> must be a Debian architecture string."
    echo "<build-dir> must be a writable directory"
    echo "<suite> must be a OpenInkpot suite, defaults to $SUITE."
}

if [ -n "$DEBUG" ]; then
    [ -f $BDBT ] || (echo "Please instal bashdb"; exit 1)
    source $BDBT -q
    _Dbg_set_trace ; : ; :
fi

if [ -n "$TRACE" ]; then
    [ -f $BDBT ] || (echo "Please install bashdb"; exit 1)
    source $BDBT -q
    _Dbg_linetrace_on
fi

# configs use this variable, so to make sure..
# Note that this is not the version, but part of package's name.
if [ -z "$GCC_VERSION" ]; then
	GCC_VERSION=4.3
fi

TEMP=$(getopt -o h --longoptions force,manual-mode,suite:,binutils-tag:,lld-tag:,gcc-tag:,glibc-tag:,uclibc-tag: -n $0 -- "$@")
if [ $? != 0 ]; then
    exit 1
fi
eval set -- "$TEMP"

while true; do
    case "$1" in
        --help) usage; exit;;
        --force) FORCED_ACTION=1; shift;;
        --manual-mode) MANUAL_MODE=1; shift;;
        # lld_TAG, binutils_TAG...
        --*-tag) eval "${${1#--}%-tag}_TAG=$2"; shift 2;;
        --suite) SUITE=$2; shift 2;;
        --) shift; break;;
        *) exit 1;;
    esac
done

TARGET="$1"
if [ -z "$TARGET" ]; then
    usage
    exit 1
fi

SRC_DIR=`pwd`

# SIGINT handler; removes cruft
# if $NO_CLEAN is set in the environment, this function does nothing
cleanup() {
	if [ -z "$NO_CLEAN" ]; then
		if [ "$SRC_DIR" != "/usr/src" ]; then
			rm -rf "$SRC_DIR"
		fi
	fi
}

# Paths to sources; this is relevant for SRC_DIR=/usr/src case
BINUTILS_DIR=$SRC_DIR/binutils
LLD_DIR=$SRC_DIR/linux-libc-dev
UCLIBC_DIR=$SRC_DIR/uclibc
GLIBC_DIR=$SRC_DIR/glibc
GCC_DIR=$SRC_DIR/gcc-$GCC_VERSION

[ -n "$BUILD_ROOTCMD" ] || BUILD_ROOTCMD=fakeroot
[ -n "$INSTALL_ROOTCMD" ] || INSTALL_ROOTCMD=sudo

# Options to apt-get source
[ -n "$APT_OPTS" ] || APT_OPTS="Acquire::Source-Symlinks=False"

MYARCH=`dpkg --print-architecture`

ARCH_INFO=$(dpkg-architecture -a$TARGET -s)
if [ -z "$ARCH_INFO" ]; then
    echo "Unknown architecture: $TARGET"
    exit 1
fi
eval "$ARCH_INFO"

case "$GCC_VERSION" in
	3.3)
		GXX_SONAME=5;;
	3.4|4.0|4.1|4.2|4.3)
		GXX_SONAME=6;;
    *)
        echo "Unknown GCC_VERSION: $GCC_VERSION"
        exit 1;;
esac
PKGLIST_GCC="gcc-${GCC_VERSION}-${DEB_HOST_GNU_TYPE} cpp-${GCC_VERSION}-${DEB_HOST_GNU_TYPE} libgcc1-${DEB_HOST_ARCH}-cross g++-${GCC_VERSION}-${DEB_HOST_GNU_TYPE} libstdc++${GXX_SONAME}-${DEB_HOST_ARCH}-cross libstdc++${GXX_SONAME}-dev-${DEB_HOST_ARCH}-cross"

# get the source package
# $1 -- package name
get_srcpkg() {
	local _pkgname="$1"

	( cd $SRC_DIR; apt-get -o $APT_OPTS source $_pkgname >&2 )
	local _version=$(apt-cache showsrc $_pkgname | awk '/^Version:/ { print $2 }' | sed -e 's,-.*,,')

	echo "$SRC_DIR/$_pkgname-$_version"
}

if [ -z $MANUAL_MODE ]; then
    echo "Get packages from Git"; exit 1;
fi

# banner
echo "Building cross toolchain packages"
echo "---------------------------------"
echo "Host architecture: $MYARCH"
echo "Target cpu: $DEB_HOST_GNU_CPU"
echo "Target os: $DEB_HOST_GNU_SYSTEM"

# clobber dpkg-architecture environment
_env() {
	unset DEB_BUILD_ARCH
	unset DEB_BUILD_ARCH_OS
	unset DEB_BUILD_ARCH_CPU
	unset DEB_BUILD_GNU_CPU
	unset DEB_BUILD_GNU_SYSTEM
	unset DEB_BUILD_GNU_TYPE
	unset DEB_HOST_ARCH
	unset DEB_HOST_ARCH_OS
	unset DEB_HOST_ARCH_CPU
	unset DEB_HOST_GNU_CPU
	unset DEB_HOST_GNU_SYSTEM
	unset DEB_HOST_GNU_TYPE
}

# get source package's version from its debian/changelog
# $1 -- path to unpacked sources
_get_version() {
	local _dir="$1"
	cd "$_dir"; dpkg-parsechangelog|awk '/Version:/ {print $2}'
}

# check for error condition, scream and die if needed
# This one should be called right after the command that
# can potentially trigger the error condition.
# $1 -- string describing the action (e.g., "installing")
# $2 -- name of the package, on which this action was performed
_checkerr() {
	local _err="$?"
	local _what="$1"
	local _pkg="$2"

	if [ $_err -ne 0 ]; then
		echo "Something wicked happened when $_what $_pkg, exiting."
		exit 1
	fi
}

# call dpkg-cross to convert a target package into a -cross package
# and perform cross-installation
# Takes paths to binary packages to be processed as arguments.
_crossinst() {
#	while [ -n "$1" ]; do
		local _pkgfile="$@"
		echo "Dpkg-crossing following packages: $1"
		( cd "$SRC_DIR"; dpkg-cross -a ${DEB_HOST_ARCH} -b ${_pkgfile} )
		( cd "$SRC_DIR"; $INSTALL_ROOTCMD dpkg-cross -a ${DEB_HOST_ARCH} \
			-i ${_pkgfile} )
		shift
#	done
}

# check if a package is installed
# $@ -- binary package names
_checkinst() {
	local _pkg
	local _status

	while [ -n "$1" ]; do
		_pkg="$1"
		_status=`dpkg -s "$_pkg" 2>/dev/null | grep '^Status: ' | cut -d' ' -f4`
		if [ "$?" != "0" -o "$_status" != "installed" ]; then
			exit
		fi

		shift
	done

	echo "installed"
}

# ------------------------------------------------------- #
# tools                                                   #
# ------------------------------------------------------- #
# These functions are responsible for building of each component
# in the toolchain. Names and code should be pretty straightforward.

############
# binutils #
############
do_binutils() {
    echo "do_binutils"

	VERSION=`_get_version "$BINUTILS_DIR"`
	PKGNAME="binutils-${DEB_HOST_GNU_TYPE}"
	
	if [ -z "`_checkinst $PKGNAME`" -o -n "$FORCED_ACTION" ]; then
		build_binutils
		install_binutils
	else
		echo "binutils ($PKGNAME) appears to be installed, skipping"
	fi
}

build_binutils() {
	pushd "$BINUTILS_DIR"
	_ARCH=$DEB_HOST_ARCH
	( _env; env TARGET="$_ARCH" \
	  $BUILD_ROOTCMD debian/rules binary-cross clean-cross )
	_checkerr building binutils
	popd
}

install_binutils() {
	VERSION=`_get_version "$BINUTILS_DIR"`
	PKGNAME="binutils-${DEB_HOST_GNU_TYPE}_${VERSION}_${DEB_BUILD_ARCH}.deb"
	$INSTALL_ROOTCMD dpkg -i "$SRC_DIR/$PKGNAME"
	_checkerr installing binutils
}

########################
# linux-libc-dev #
########################
do_lld() {
    echo "do_lld"

	VERSION=`_get_version "$LLD_DIR"`
	PKGNAME="linux-libc-dev-${DEB_HOST_ARCH}-cross"
	
	if [ -z "`_checkinst $PKGNAME`" -o -n "$FORCED_ACTION" ]; then
		build_lld
		install_lld
	else
		echo "linux-libc-dev ($PKGNAME) appears to be installed, skipping"
	fi
}

build_lld() {
	pushd "$LLD_DIR"
	SOURCEVERSION=`_get_version "$LLD_DIR"`
	VERSION=$(echo $SOURCEVERSION |sed "s/-.*//")
	dpkg-buildpackage -uc -us -r$BUILD_ROOTCMD -a${DEB_HOST_ARCH} -d -b
	_checkerr building linux-libc-dev
	$BUILD_ROOTCMD debian/rules clean
	popd
}

install_lld() {
	VERSION=`_get_version "$LLD_DIR"`
	PKGNAME="linux-libc-dev_${VERSION}_${DEB_HOST_ARCH}.deb"
	_crossinst $PKGNAME
	_checkerr installing linux-libc-dev
}

##### c libraries #####
do_stage1_libc() {
    echo "do_stage1_libc"

    case "$DEB_HOST_GNU_SYSTEM" in
        *uclibc*) do_uclibc_bs;;
   	*gnu*) do_glibc_bs;;
        *) echo "Unknown OS"; exit 1;;
    esac
}

do_stage2_libc() {
    echo "do_stage2_libc"

    case "$DEB_HOST_GNU_SYSTEM" in
        *uclibc*) do_uclibc;;
        *gnu*) do_glibc_bs2;;
        *) echo "Unknown OS"; exit 1;;
	esac
}

##########
# uclibc #
##########
do_uclibc_bs() {
	VERSION=`_get_version "$UCLIBC_DIR"`
	PKGNAME1="libuclibc-bootstrap-${DEB_HOST_ARCH}-cross"

	if [ -z "`_checkinst $PKGNAME1`" -o -n "$FORCED_ACTION" ]; then
		if [ -z "`_checkinst $PKGNAME1`" -o -n "$FORCED_ACTION" ]; then
			build_uclibc_bs
			install_uclibc_bs
		else
			echo "uclibc ($PKGNAME1) appears to be installed, skipping"
		fi
	else
		echo "uclibc ($PKGNAME1) appears to be installed, skipping"
	fi
}

build_uclibc_bs() {
	pushd "$UCLIBC_DIR"
	( env DEB_CROSS_BOOTSTRAP=yes \
		dpkg-buildpackage -uc -us -r$BUILD_ROOTCMD -a${DEB_HOST_ARCH} \
		-b )
	_checkerr building "bootstrap uclibc"
	$BUILD_ROOTCMD debian/rules clean
	popd
}

install_uclibc_bs() {
	VERSION=`_get_version "$UCLIBC_DIR"`
	PKGNAME="libuclibc-bootstrap_${VERSION}_${DEB_HOST_ARCH}.deb"
	_crossinst $PKGNAME
	_checkerr installing "bootstrap uclibc"
}

do_uclibc() {
	VERSION=`_get_version "$UCLIBC_DIR"`
	PKGNAME="libuclibc0-${DEB_HOST_ARCH}-cross libuclibc-dev-${DEB_HOST_ARCH}-cross"

	if [ -z "`_checkinst $PKGNAME`" -o -n "$FORCED_ACTION" ]; then
		build_uclibc
		install_uclibc
	else
		echo "uclibc ($PKGNAME) appears to be installed, skipping"
	fi
}

build_uclibc() {
	$INSTALL_ROOTCMD dpkg -P libuclibc-bootstrap-${DEB_HOST_ARCH}-cross
	pushd "$UCLIBC_DIR"
	( dpkg-buildpackage -uc -us -r$BUILD_ROOTCMD -a${DEB_HOST_ARCH} -b )
	_checkerr building uclibc
	$BUILD_ROOTCMD debian/rules clean
	popd
}

install_uclibc() {
	VERSION=`_get_version "$UCLIBC_DIR"`
	PKGPREFIX="${VERSION}_${DEB_HOST_ARCH}.deb"
	PKGNAMES="libuclibc-dev_${PKGPREFIX} ldso-uclibc_${PKGPREFIX} libc-uclibc_${PKGPREFIX} libm-uclibc_${PKGPREFIX} libpthread-uclibc_${PKGPREFIX} libdl-uclibc_${PKGPREFIX} librt-uclibc_${PKGPREFIX} libresolv-uclibc_${PKGPREFIX} libcrypt-uclibc_${PKGPREFIX} libutil-uclibc_${PKGPREFIX} libnsl-uclibc_${PKGPREFIX}"
	echo "Installing Uclibc packages: $PKGNAMES"
	_crossinst $PKGNAMES
	_checkerr installing uclibc
}

#########
# glibc #
#########
do_glibc_bs() {
	VERSION=`_get_version "$GLIBC_DIR"`
	PKGNAME1="libc6-dev-headers-${DEB_HOST_ARCH}-cross"
	PKGNAME2="libc6-${DEB_HOST_ARCH}-cross libc6-dev-${DEB_HOST_ARCH}-cross"

	if [ -z "`_checkinst $PKGNAME2`" -o -n "$FORCED_ACTION" ]; then
		if [ -z "`_checkinst $PKGNAME1`" -o -n "$FORCED_ACTION" ]; then
			build_glibc_bs
			install_glibc_bs
		else
			echo "glibc ($PKGNAME1) appears to be installed, skipping"
		fi
	else
		echo "glibc ($PKGNAME2) appears to be installed, skipping"
	fi
}

build_glibc_bs() {
	pushd "$GLIBC_DIR"
	( env DEB_CROSS_BOOTSTRAP=yes \
		dpkg-buildpackage -uc -us -r$BUILD_ROOTCMD -a${DEB_HOST_ARCH} \
		-b )
	_checkerr building "bootstrap glibc"
	$BUILD_ROOTCMD debian/rules clean
	popd
}

install_glibc_bs() {
	VERSION=`_get_version "$GLIBC_DIR"`
	PKGNAME="libc6-dev-headers_${VERSION}_${DEB_HOST_ARCH}.deb"
	_crossinst $PKGNAME
	_checkerr installing "bootstrap glibc"
}

do_glibc_bs2() {
	VERSION=`_get_version "$GLIBC_DIR"`
	PKGNAME="libc6-${DEB_HOST_ARCH}-cross libc6-dev-${DEB_HOST_ARCH}-cross"

	if [ -z "`_checkinst $PKGNAME`" -o -n "$FORCED_ACTION" ]; then
		build_glibc_bs2
		install_glibc_bs2
	else
		echo "glibc ($PKGNAME) appears to be installed, skipping"
	fi
}

build_glibc_bs2() {
	pushd "$GLIBC_DIR"
	( env DEB_CROSS_BOOTSTRAP=second \
		dpkg-buildpackage -uc -us -r$BUILD_ROOTCMD -a${DEB_HOST_ARCH} \
		-b )
	_checkerr building glibc
	$BUILD_ROOTCMD debian/rules clean
	popd
}

install_glibc_bs2() {
	$INSTALL_ROOTCMD dpkg -P libc6-dev-headers-${DEB_HOST_ARCH}-cross
	VERSION=`_get_version "$GLIBC_DIR"`
	PKGPREFIX="${VERSION}_${DEB_HOST_ARCH}.deb"
	PKGNAMES="libc6_${PKGPREFIX} libc6-dev_${PKGPREFIX}"
	_crossinst $PKGNAMES
	_checkerr installing glibc
}

do_glibc() {
	build_glibc
	install_glibc
}

build_glibc() {
	pushd "$GLIBC_DIR"
	( dpkg-buildpackage -uc -us -r$BUILD_ROOTCMD -a${DEB_HOST_ARCH} -b )
	_checkerr building glibc
	$BUILD_ROOTCMD debian/rules clean
	popd
}

install_glibc() {
	VERSION=`_get_version "$GLIBC_DIR"`
	PKGPREFIX="${VERSION}_${DEB_HOST_ARCH}.deb"
	PKGNAMES="libc6_${PKGPREFIX} libc6-dev_${PKGPREFIX}"
	_crossinst $PKGNAMES
	_checkerr installing glibc
}

#######
# gcc #
#######
do_stage1() {
    echo "do_stage1"

	VERSION=`_get_version "$GCC_DIR"`
	PKGPREFIX1="${GCC_VERSION}-${DEB_HOST_GNU_TYPE}"
	PKGPREFIX2="${DEB_HOST_ARCH}-cross"
	PKGNAMES="gcc-${PKGPREFIX1} gcc-${PKGPREFIX1}-base cpp-${PKGPREFIX1} libgcc1-${PKGPREFIX2}"

	if [ -z "`_checkinst $PKGNAMES`" -o -n "$FORCED_ACTION" ]; then
		do_stage1_libc
		build_gcc_bs
		remove_native_toolchain
		install_gcc_bs
		if [ "x$MYARCH" = "x$DEB_HOST_ARCH" ]; then
		    install_virtual_bs_toolchain
		fi
	else
		echo "base compiler ($PKGNAMES) appears to be installed, skipping"
	fi
}

build_gcc_bs() {
	pushd "$GCC_DIR"
	ARCH=${DEB_HOST_ARCH}
	( _env; env GCC_TARGET=${ARCH} DEB_CROSS=yes DEB_CROSS_BOOTSTRAP=yes \
		dpkg-buildpackage -uc -us -r$BUILD_ROOTCMD -b -d )
	_checkerr building "bootstrap gcc"
	$BUILD_ROOTCMD debian/rules clean
	popd
}

install_gcc_bs() {
	VERSION=`_get_version "$GCC_DIR"`
	PKGPREFIX1="${GCC_VERSION}-${DEB_HOST_GNU_TYPE}_${VERSION}_${DEB_BUILD_ARCH}.deb"
	PKGPREFIX2="${GCC_VERSION}-${DEB_HOST_GNU_TYPE}-base_${VERSION}_${DEB_BUILD_ARCH}.deb"
	PKGPREFIX3="${DEB_HOST_ARCH}-cross_${VERSION}_all.deb"
	PKGNAMES="gcc-${PKGPREFIX1} gcc-${PKGPREFIX2} cpp-${PKGPREFIX1} libgcc1-${PKGPREFIX3}"
	( cd "$SRC_DIR"; $INSTALL_ROOTCMD dpkg -i --force-depends $PKGNAMES )
	_checkerr installing "bootstrap gcc"
}

do_stage2() {
	VERSION=`_get_version "$GCC_DIR"`
	PKGPREFIX1="${GCC_VERSION}-${DEB_HOST_GNU_TYPE}"
	PKGPREFIX2="${DEB_HOST_ARCH}-cross"
	PKGNAMES="gcc-${PKGPREFIX1} gcc-${PKGPREFIX1}-base cpp-${PKGPREFIX1} g++-${PKGPREFIX1} libgcc1-${PKGPREFIX2} libstdc++6-${PKGPREFIX2} libstdc++6-${GCC_VERSION}-dev-${PKGPREFIX2}"

	if [ -z "`_checkinst $PKGNAMES`" -o -n "$FORCED_ACTION" ]; then
		do_stage2_libc
		if [ "x$MYARCH" = "x$DEB_HOST_ARCH" ]; then
		    remove_cross_bs_toolchain
		fi
		install_native_toolchain
		build_gcc
		remove_native_toolchain
		install_gcc
		if [ "x$MYARCH" = "x$DEB_HOST_ARCH" ]; then
		    install_virtual_toolchain
		fi
	else
		echo "compiler ($PKGNAMES) appears to be installed, skipping"
	fi
}

build_gcc() {
	$INSTALL_ROOTCMD dpkg -P ${PKGLIST_GCC}
	pushd "$GCC_DIR"
	ARCH=${DEB_HOST_ARCH}
	( _env; env GCC_TARGET=${ARCH} DEB_CROSS=yes DEB_TARGET_LIBCXX=yes \
		dpkg-buildpackage -uc -us -r$BUILD_ROOTCMD -d )
	_checkerr building gcc
	$BUILD_ROOTCMD debian/rules clean
	popd
}

install_gcc() {
	VERSION=`_get_version "$GCC_DIR"`
	PKGPREFIX1="${GCC_VERSION}-${DEB_HOST_GNU_TYPE}_${VERSION}_${DEB_BUILD_ARCH}.deb"
	PKGPREFIX0="${GCC_VERSION}-${DEB_HOST_GNU_TYPE}-base_${VERSION}_${DEB_BUILD_ARCH}.deb"
	PKGPREFIX2="${DEB_HOST_ARCH}-cross_${VERSION}_all.deb"
	PKGNAMES="gcc-${PKGPREFIX1} gcc-${PKGPREFIX0} cpp-${PKGPREFIX1} g++-${PKGPREFIX1} libgcc1-${PKGPREFIX2} libstdc++6-${PKGPREFIX2} libstdc++6-${GCC_VERSION}-dev-${PKGPREFIX2}"
	( cd "$SRC_DIR"; $INSTALL_ROOTCMD dpkg -i $PKGNAMES )
	_checkerr installing gcc
}

# -- toolchain metapackage --

install_cross_toolchain_pkg() {
	# render package's "Depends:" header
	BINUTILS_VERSION=`_get_version "$BINUTILS_DIR"`
	BINUTILS_PKGDEP="binutils-${DEB_HOST_GNU_TYPE} (= ${BINUTILS_VERSION})"

	LLD_VERSION=`_get_version "$LLD_DIR"`
	LLD_PKGDEP="linux-libc-dev-${DEB_HOST_ARCH}-cross (= ${LLD_VERSION})"

	GCCPKG_VERSION=`_get_version "$GCC_DIR"`
	GCC_PKGDEP="gcc-${GCC_VERSION}-${DEB_HOST_GNU_TYPE} (= ${GCCPKG_VERSION}), gcc-${GCC_VERSION}-${DEB_HOST_GNU_TYPE}-base (= ${GCCPKG_VERSION}), cpp-${GCC_VERSION}-${DEB_HOST_GNU_TYPE} (= ${GCCPKG_VERSION}), g++-${GCC_VERSION}-${DEB_HOST_GNU_TYPE} (= ${GCCPKG_VERSION}), libgcc1-${DEB_HOST_ARCH}-cross (= ${GCCPKG_VERSION}), libstdc++6-${DEB_HOST_ARCH}-cross (= ${GCCPKG_VERSION}), libstdc++6-${GCC_VERSION}-dev-${DEB_HOST_ARCH}-cross (= ${GCCPKG_VERSION})"

    if [ "x$MYARCH" = "x$DEB_HOST_ARCH" ]; then
        CONFLICTS="cpp-${GCC_VERSION}, gcc-${GCC_VERSION}, g++-${GCC_VERSION}, libstdc++6-dev"
    else
        CONFLICTS=""
    fi

	DEPENDS="$BINUTILS_PKGDEP, $LLD_PKGDEP, $GCC_PKGDEP,"

    case "$DEB_HOST_ARCH_OS" in
        uclibc)
	        UCLIBC_VERSION=`_get_version "$UCLIBC_DIR"`
	        UCLIBC_PKGDEP="libuclibc0-${DEB_HOST_ARCH}-cross (= ${UCLIBC_VERSION}), libuclibc-dev-${DEB_HOST_ARCH}-cross (= ${UCLIBC_VERSION})"
		    DEPENDS="$DEPENDS $UCLIBC_PKGDEP";;
	    linux)
	        GLIBC_VERSION=`_get_version "$GLIBC_DIR"`
	        GLIBC_PKGDEP="libc6-${DEB_HOST_ARCH}-cross (= ${GLIBC_VERSION}), libc6-dev-${DEB_HOST_ARCH}-cross (= ${GLIBC_VERSION})"
		    DEPENDS="$DEPENDS $GLIBC_PKGDEP";;
        *)
            echo "Unknown OS"; exit 1;;
    esac

	if [ -z "$TPKG_MAINTAINER" ]; then
		TPKG_MAINTAINER="Alexander Shishkin <virtuoso@slind.org>"
	fi

	TPKG_PKGNAME="${DEB_HOST_ARCH}-cross-toolchain"
	TPKG_PKGDIR=$SRC_DIR/$TPKG_PKGNAME

	TPKG_VERSION="${TP_VERSION}+binutils${BINUTILS_VERSION}+linux-libc-dev${LLD_VERSION}+gcc${GCCPKG_VERSION}"
    case "$DEB_HOST_ARCH_OS" in
        uclibc)
            TPKG_VERSION="${TPKG_VERSION}+uclibc${UCLIBC_VERSION}";;
        linux)
            TPKG_VERSION="${TPKG_VERSION}+glibc${GLIBC_VERSION}";;
        *)
            echo "Unknown OS"; exit 1;;
    esac

    TPKG_VERSION=$(echo $TPKG_VERSION | sed -e 's,-,+,g')

	mkdir -p $TPKG_PKGDIR/DEBIAN

	cat > $TPKG_PKGDIR/DEBIAN/control <<EOF
Package: $TPKG_PKGNAME
Version: $TPKG_VERSION
Section: host-tools
Priority: optional
Architecture: $DEB_BUILD_ARCH
Depends: $DEPENDS
Conflicts: $CONFLICTS
Source: toolchain-package
Provides: build-essential-${DEB_BUILD_ARCH}-cross, cross-toolchain-${DEB_HOST_ARCH}-cross, cross-toolchain-${DEB_HOST_ARCH}-dcv1
Installed-size: 0
Maintainer: $TPKG_MAINTAINER
Description: cross-compilation toolchain for $DEB_HOST_ARCH
 This is a metapackage that will get you a complete toolchain
 for cross-compilation into $DEB_HOST_ARCH target.
EOF

	dpkg-deb -b $TPKG_PKGDIR
    $INSTALL_ROOTCMD dpkg -i $SRC_DIR/${TPKG_PKGNAME}.deb
	dpkg-name -o $SRC_DIR/${TPKG_PKGNAME}.deb
}

install_virtual_toolchain() {
	TPKG_PKGNAME="${DEB_HOST_ARCH}-toolchain"
	TPKG_PKGDIR=$SRC_DIR/$TPKG_PKGNAME

	GCCPKG_VERSION=`_get_version "$GCC_DIR"`
    DEPENDS="g++-${GCC_VERSION}-${DEB_HOST_GNU_TYPE} (= ${GCCPKG_VERSION}),"

    case "$DEB_HOST_ARCH_OS" in
        uclibc)
	        UCLIBC_VERSION=`_get_version "$UCLIBC_DIR"`
            DEPENDS="${DEPENDS} libuclibc-dev-${DEB_HOST_ARCH}-cross (= ${UCLIBC_VERSION})";;
        linux)
	        GLIBC_VERSION=`_get_version "$GLIBC_DIR"`
            DEPENDS="${DEPENDS} libc6-dev-${DEB_HOST_ARCH}-cross (= ${GLIBC_VERSION})";;
        *)
            echo "Unknown OS"; exit 1;;
    esac
	
	if [ -z "$TPKG_MAINTAINER" ]; then
		TPKG_MAINTAINER="Alexander Shishkin <virtuoso@slind.org>"
	fi
	
	mkdir -p $TPKG_PKGDIR/DEBIAN

	cat > $TPKG_PKGDIR/DEBIAN/control <<EOF
Package: $TPKG_PKGNAME
Version: 0.2
Section: host-tools
Priority: optional
Architecture: all
Depends: ${DEPENDS}
Source: toolchain-package
Conflicts: gcc-${GCC_VERSION}, cpp-${GCC_VERSION}, g++-${GCC_VERSION}, gcc, cpp, g++
Provides: gcc-${GCC_VERSION}, cpp-${GCC_VERSION}, g++-${GCC_VERSION}, gcc, cpp, g++
Installed-size: 4
Maintainer: $TPKG_MAINTAINER
Description: Meta-package to remove native Debian toolchain
 WARNING! WARNING! WARNING!
 By installing this package, you confirm that you do not want to compile
 anything with native compiler anymore. You confirm that you do not care whether
 anything compiled with Slind's compiler would run on your Debian system or not.
EOF

	mkdir -p $TPKG_PKGDIR/usr/share/doc/$TPKG_PKGNAME
	cat > $TPKG_PKGDIR/usr/share/doc/$TPKG_PKGNAME/changelog <<EOF
$TPKG_PKGNAME (0.2) unstable; urgency=low

  * Initial release.

 -- $TPKG_MAINTAINER  `date --rfc-822`
EOF

	mkdir -p $TPKG_PKGDIR/usr/bin
	
	# Install symlinks.
	ln -s /usr/bin/${DEB_HOST_GNU_TYPE}-gcc-${GCC_VERSION} $TPKG_PKGDIR/usr/bin/cc
	ln -s /usr/bin/${DEB_HOST_GNU_TYPE}-gcc-${GCC_VERSION} $TPKG_PKGDIR/usr/bin/gcc
	ln -s /usr/bin/${DEB_HOST_GNU_TYPE}-cpp-${GCC_VERSION} $TPKG_PKGDIR/usr/bin/cpp
	ln -s /usr/bin/${DEB_HOST_GNU_TYPE}-g++-${GCC_VERSION} $TPKG_PKGDIR/usr/bin/g++
	ln -s /usr/bin/${DEB_HOST_GNU_TYPE}-gcc-${GCC_VERSION} $TPKG_PKGDIR/usr/bin/gcc-${GCC_VERSION} 
	ln -s /usr/bin/${DEB_HOST_GNU_TYPE}-cpp-${GCC_VERSION} $TPKG_PKGDIR/usr/bin/cpp-${GCC_VERSION} 
	ln -s /usr/bin/${DEB_HOST_GNU_TYPE}-g++-${GCC_VERSION} $TPKG_PKGDIR/usr/bin/g++-${GCC_VERSION}

	dpkg-deb -b $TPKG_PKGDIR
	$INSTALL_ROOTCMD dpkg -i $SRC_DIR/${TPKG_PKGNAME}.deb
	dpkg-name -o $SRC_DIR/${TPKG_PKGNAME}.deb
}

remove_native_toolchain() {
	if [ "x$MYARCH" = "x$DEB_HOST_ARCH" ]; then
	    $INSTALL_ROOTCMD apt-get -y --force-yes remove gcc-$GCC_VERSION cpp-$GCC_VERSION gcc cpp
	fi
}

install_native_toolchain() {
	if [ "x$MYARCH" = "x$DEB_HOST_ARCH" ]; then
	    $INSTALL_ROOTCMD env $PROXYENV apt-get -y --force-yes install gcc-$GCC_VERSION cpp-$GCC_VERSION g++-$GCC_VERSION gcc cpp g++
    fi
}

install_virtual_bs_toolchain() {
	TPKG_PKGNAME="${DEB_HOST_ARCH}-bootstrap-toolchain"
	TPKG_PKGDIR=$SRC_DIR/$TPKG_PKGNAME

	if [ -z "$TPKG_MAINTAINER" ]; then
		TPKG_MAINTAINER="Alexander Shishkin <virtuoso@slind.org>"
	fi
	
	mkdir -p $TPKG_PKGDIR/DEBIAN

	cat > $TPKG_PKGDIR/DEBIAN/control <<EOF
Package: $TPKG_PKGNAME
Version: 0.2
Section: host-tools
Priority: optional
Architecture: all
Depends: gcc-${GCC_VERSION}-${DEB_HOST_GNU_TYPE} (= ${GCCPKG_VERSION}), cpp-${GCC_VERSION}-${DEB_HOST_GNU_TYPE} (= ${GCCPKG_VERSION})
Source: toolchain-package
Conflicts: gcc-${GCC_VERSION}, cpp-${GCC_VERSION}
Provides: gcc-${GCC_VERSION}, cpp-${GCC_VERSION}, gcc, cpp
Installed-size: 4
Maintainer: $TPKG_MAINTAINER
Description: Meta-package to remove native Debian toolchain
 WARNING! WARNING! WARNING!
 By installing this package, you confirm that you do not want to compile
 anything with native compiler anymore. You confirm that you do not care whether
 anything compiled with Slind's compiler would run on your Debian system or not.
EOF

	mkdir -p $TPKG_PKGDIR/usr/share/doc/$TPKG_PKGNAME
	cat > $TPKG_PKGDIR/usr/share/doc/$TPKG_PKGNAME/changelog <<EOF
$TPKG_PKGNAME (0.2) unstable; urgency=low

  * Initial release.

 -- $TPKG_MAINTAINER  `date --rfc-822`
EOF

	mkdir -p $TPKG_PKGDIR/usr/bin
	
	# Install symlinks.
	ln -s /usr/bin/${DEB_HOST_GNU_TYPE}-gcc-${GCC_VERSION} $TPKG_PKGDIR/usr/bin/cc
	ln -s /usr/bin/${DEB_HOST_GNU_TYPE}-gcc-${GCC_VERSION} $TPKG_PKGDIR/usr/bin/gcc
	ln -s /usr/bin/${DEB_HOST_GNU_TYPE}-cpp-${GCC_VERSION} $TPKG_PKGDIR/usr/bin/cpp
	ln -s /usr/bin/${DEB_HOST_GNU_TYPE}-gcc-${GCC_VERSION} $TPKG_PKGDIR/usr/bin/gcc-${GCC_VERSION} 
	ln -s /usr/bin/${DEB_HOST_GNU_TYPE}-cpp-${GCC_VERSION} $TPKG_PKGDIR/usr/bin/cpp-${GCC_VERSION} 

	dpkg-deb -b $TPKG_PKGDIR
	$INSTALL_ROOTCMD dpkg -i $SRC_DIR/${TPKG_PKGNAME}.deb
	dpkg-name -o $SRC_DIR/${TPKG_PKGNAME}.deb
}

remove_cross_bs_toolchain() {
	GCC_PKG="gcc-${GCC_VERSION}-${DEB_HOST_GNU_TYPE} gcc-${GCC_VERSION}-${DEB_HOST_GNU_TYPE}-base  cpp-${GCC_VERSION}-${DEB_HOST_GNU_TYPE} libgcc1-${DEB_HOST_ARCH}-cross ${DEB_HOST_ARCH}-bootstrap-toolchain"

	$INSTALL_ROOTCMD apt-get -y --force-yes remove $GCC_PKG
}

do_binutils
do_lld
do_stage1
do_stage2
case "$DEB_HOST_GNU_SYSTEM" in
    *uclibc*)
        ;;
    *gnu*)
        build_glibc
        install_glibc;;
    *)
        echo "Unknown OS";;
esac

do_cross_toolchain_pkg
install_cross_toolchain_pkg
